#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

######################################################################

set -e
. pipestatus

if test "$THIS_IS_ME"; then
    . ./distbb.conf
else
    . @@SYSCONFDIR@@/distbb.conf
fi

######################################################################

header (){
    printf ' --**--**-- %8s --**--**--\n' "$1"
}

######################################################################

build_package (){
    for t in init $TARGETS; do
	header $t
	case "$t" in
	    init)
		rm -rf $DEL_DIRS
		cd /
		if test "$BOOTSTRAP"; then
		    gzip -dc "$BOOTSTRAP" | tar -cf-
		fi
		cd $PKGSRCDIR/$1;;
	    delete)
		$PKG_DELETE "$($BMAKE show-var VARNAME=PKGNAME)";;
	    *)
		$BMAKE $t;;
	esac
    done
}

while read pkgpath; do
    if runpipe_re '. 0' build_package $pkgpath '|' uuencode -; then
	echo "status: $pipestatus_1"
    else
	echo "status: 1" # uuencode failed
    fi
    echo '' # end of task
done
