#!/bin/sh

# Copyright (c) 2007-2008 Aleksey Cheusov <vle@gmx.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

######################################################################

set -e
. pipestatus

export LC_ALL=C # for sort and uniq

######################################################################

verbose_print (){
    printf "$1" 1>&2
}

set_if_not_set (){
    # $1 - varname
    # $2 - value
    if eval test -z "\$$1"; then
	eval $1="'$2'"
    fi
}

######################################################################

set_if_not_set BMAKE           make
set_if_not_set PKGSRCDIR       /usr/pkgsrc
set_if_not_set PKG_SRC_SUMMARY $PKGSRCDIR/pkg_src_summary.txt
set_if_not_set PACKAGES        $PKGSRCDIR/packages
set_if_not_set PKG_SUMMARY     $PACKAGES/pkg_summary.gz
set_if_not_set PKG_SUFX        .tgz
set_if_not_set REPORTS_DIR     $HOME/bulk-logs
set_if_not_set TARGETS         'clean checksum depends build install package'
set_if_not_set TRANSPORT       'ssh -x'

######################################################################

verbose_print "Preparations\n"

rm -rf $REPORTS_DIR

tmpdir=$REPORTS_DIR/_distbb/tmp
mkdir -p -m 700 $tmpdir

######################################################################
### extracting DEPENDS and BUILDS_DEPENDS
extract_depends (){
    awk -v deps_fn="$deps_fn" -v bdeps_fn="$bdeps_fn" '
/^PKGNAME=/ {
   pkgname = substr($0, 9)
   next
}

/^PKGPATH=/ {
   pkgpath = substr($0, 9)
   next
}

/^DEPENDS=/ {
   $0 = substr($0, 9)
   gsub(/[^ \t]+:[.][.]\/[.][.]\//, "")

   for (i=1; i <= NF; ++i){
      deps [$i] = 1
   }
   for (i in deps){
      print pkgname, i, pkgpath > deps_fn
   }
   delete deps

   next
}

/^BUILD_DEPENDS=/ {
   $0 = substr($0, 15)
   gsub(/[^ \t]+:[.][.]\/[.][.]\//, "")

   for (i=1; i <= NF; ++i){
      deps [$i] = 1
   }
   for (i in deps){
      print pkgname, i, pkgpath > bdeps_fn
   }
   delete deps

   next
}

NF == 0 && curr_pkgpath == pkgpath {
   print pkgname
   print deps
   print bdeps
}
' $PKG_SRC_SUMMARY
}

deps_fn=$tmpdir/deps.txt
bdeps_fn=$tmpdir/bdeps.txt

verbose_print "  Dependencies from pkg_src_summary file..."
extract_depends
verbose_print "done\n"

######################################################################
### input: graph as a list of arcs
### output: transitive close of this graph
transitive_closure (){
    awk '
# AWK badly suits for this task :-(

BEGIN {
   SUBSEP = " "
}

{
   arc [$1, $2] = 1

   outgoing [$1] = outgoing [$1] " " $2
   incoming [$2] = incoming [$2] " " $1

   nodes [$1] = 1
   nodes [$2] = 1
}

END {
   for (k in nodes){
      cnt_i = split(incoming [k], arr_i)
      for (ii = 1; ii <= cnt_i; ++ii){
         i = arr_i [ii]

         cnt_j = split(outgoing [k], arr_j)
         for (jj = 1; jj <= cnt_j; ++jj){
            j = arr_j [jj]
            if (! ((i SUBSEP j) in arc)){
               arc [i, j] = 1
               incoming [j] = incoming [j] " " i
               outgoing [i] = outgoing [i] " " j
            }
         }
      }
   }

   for (idx in arc){
      print idx
   }
}
' "$@"
}

######################################################################
### unpacking pkg_summary if it is needed
txt_summary=$tmpdir/pkg_summary.txt
if echo $PKG_SUMMARY | grep '[.]gz$' > /dev/null; then
    gzip -dc $PKG_SUMMARY > $txt_summary
    PKG_SUMMARY=$txt_summary
elif echo $PKG_SUMMARY | grep '[.]bz2$' > /dev/null; then
    bzip2 -dc $PKG_SUMMARY > $txt_summary
    PKG_SUMMARY=$txt_summary
fi

######################################################################
### comparison binaries against pkgsrc tree
verbose_print "  pkg_summary vs. pkg_src_summary comparison..."
cmp_fn=$tmpdir/cmp.txt
pkg_cmp_summary -p $PKG_SUMMARY $PKG_SRC_SUMMARY > $cmp_fn
verbose_print "done\n"

######################################################################
### direct packages that need to be rebuilt
verbose_print "  List of packages to be built..."
rebuild1_fn=$tmpdir/rebuild1.txt
awk '($1 != "=") && ($1 != "-") {print $2}' $cmp_fn |
head -40 > $rebuild1_fn
verbose_print "done\n"

######################################################################
### all dependancies (transitive closure)
extract_dep (){
    awk '
NF == 3 {
   print $2, $3
}' "$@"
}

verbose_print "  Transitive closure for the dependancy graph..."
trans_clos_fn=$tmpdir/trans_closure.txt
runpipe0 \
    extract_dep $deps_fn $bdeps_fn '|' \
    transitive_closure > $trans_clos_fn
verbose_print "done\n"

######################################################################
### only those dependancies that depend on packages that need to be rebuilt
filter_rebuild1 (){
    awk -v rebuild1_fn="$rebuild1_fn" '
BEGIN {
   while (getline < rebuild1_fn){
      hash [$1] = 1
   }
}

$1 in hash {
   print $0
}
' "$@"
}

######################################################################
verbose_print "  Packages to be built with their dependancies..."
trans_clos_rebuild_fn=$tmpdir/trans_closure_rebuild.txt
filter_rebuild1 $trans_clos_fn > $trans_clos_rebuild_fn
verbose_print "done\n"

######################################################################
### counted list of packages / queue
queue_fn=$tmpdir/queue.txt
count_deps (){
awk '
NF == 2 { count [$2] += 1 }
NF == 1 { count [$1] += 0 }
END {
   for (i in count)
      print i, count [i]
}
' "$@"
}

verbose_print "  Initial queue..."
count_deps $rebuild1_fn $trans_clos_rebuild_fn > $queue_fn
verbose_print "done\n"

queue__ready_to_be_built (){
    awk '$2 == 0 {print $1}' $queue_fn
}

######################################################################
verbose_print "  Directories for logging..."
( cd $REPORTS_DIR && awk '{print $1}' $queue_fn | xargs mkdir -p )
verbose_print "done\n"

######################################################################
### main loop - building
lckfile=$tmpdir/.lock

get_pkgpath (){
    awk -v tmp_queue_fn="$queue_fn.tmp" '
$2 == 0 {
   printf "" > tmp_queue_fn
   print $1
   ok = 1
   next
}

{
   print > tmp_queue_fn
}

END {
   exit (ok != 1)
}
' $queue_fn
}

tasks_fn=$tmpdir/tasks.txt
print_tasks (){
    i=0
    while test -s $queue_fn; do
	while ! shlock -p $$ -f ${lckfile}; do
	    sleep 1 # This is ugly but works
	done

	if get_pkgpath > $tasks_fn; then
#	    echo get_pkgpath succeeded 1>&2
	    cp ${queue_fn} $queue_fn.$i.tmp
	    mv ${queue_fn}.tmp $queue_fn
	    i=$(($i+1))

	    rm ${lckfile}
	    cat $tasks_fn
	else
#	    echo get_pkgpath failed 1>&2
	    rm ${lckfile}
	    sleep 5
	fi
    done
}

environ="BMAKE=$BMAKE PKGSRCDIR=$PKGSRCDIR REPORTS_DIR=$REPORTS_DIR TARGETS='$TARGETS'"

postfilter (){
    # postprocessor for paexec's outout.
    # It show progress suceess and failure messages,
    # redirects build logs to bulk_log/pkgpath directory,
    # recalculates counters in a queue file
    # removes unneeded bulk_log/pkgpath directories etc.
awk \
   -v trans_clos_fn=$trans_clos_rebuild_fn \
   -v queue_fn=$queue_fn \
   -v lckfile=$lckfile \
   -v reports_dir=$REPORTS_DIR \
   -v pid=$$ '
BEGIN {
   while (xgetline0(trans_clos_fn)){
      deps [$1, $2] = 1
      all_pkgpaths [$1] = 1
      all_pkgpaths [$2] = 1
   }
   xclose(trans_clos_fn)

   tmp_fn = (queue_fn ".tmp2")
   wait_for_lock=sprintf("/bin/sh -c \"while ! shlock -p %s -f %s; do sleep 1; done\"", pid, lckfile)
   rm_lock=sprintf("rm %s", lckfile)
}

!($2 in pkgpaths) {
   pkgpaths [$2] = $3
   print "started:", $3, "on", $1

   next
}

$3 == "status:" {
   status [$2] = $4
   next
}

{
   log_dir = reports_dir "/" pkgpaths [$2]
   log_fn  = log_dir "/uu.tmp"
}

NF > 2 {
   sub(/^[^ ]+ [^ ]+ /, "")
   print > log_fn
   next
}

# end of task
{
   xclose(log_fn)
}

function xsystem (prog){
   if (system(prog)){
      print "system() failed" > "/dev/stderr"
      exit 1
   }
}

function xclose (fn){
   if (close(fn)){
      print "close(\"" fn "\") failed" > "/dev/stderr"
      exit 1
   }
}

function xgetline0 (fn,                 ret){
   ret = (getline < fn)
   if (ret < 0){
      print "The function getline failed" > "/dev/stderr"
      exit 1
   }
   return (ret > 0)
}

status [$2] == 0 {
   # succeeded
   pkgpath = pkgpaths [$2]

   print "succeeded:", pkgpath

   # getting lock
   xsystem(wait_for_lock)

   # reading counts
   delete counts
   while (xgetline0(queue_fn)){
      counts [$1] = $2
   }
   xclose(queue_fn)

   # updating counts
   for (i in counts){
      if ((pkgpath SUBSEP i) in deps){
         --counts [i]
      }
   }

   # writing counts
   printf "" > tmp_fn
   for (i in counts){
      print i, counts [i] > tmp_fn
   }
   xclose(tmp_fn)

   # renaming
   xsystem("mv " tmp_fn " " queue_fn)

   # removing lock
   xsystem(rm_lock)

   # removing log directory
   xsystem("rm -rf " log_dir)

   next
}

function decode_logs (uu,                  txt,fn,dir){
   txt = uu
   sub(/[.][^.\/]*$/, ".txt", txt)

   dir = uu
   sub(/\/[^\/]*$/, "", dir)

   xsystem("uudecode -p < " uu " > " txt)

   #
   fn = ""
   while (xgetline0(txt)){
      if ($1 == "--**--**--" && $3 == "--**--**--"){
         if (fn){
            xclose(fn) # in order to not exceed system/awk limits...
         }

         fn = dir "/stage_" $2 ".txt"
         printf "  " > fn
         continue
      }

      if (fn){
         print > fn
      }else{
         print "this should not happen!" > "/dev/stderr"
      }
   }

   if (fn){
      close(fn) # in order to not exceed system/awk limits...
   }

   xsystem("rm " uu " " txt)
}

{
   # fialed
   pkgpath = pkgpaths [$2]

   print "FAILED:", pkgpath

   # getting lock
   xsystem(wait_for_lock)

   # decoding logs
   decode_logs(log_fn)

   # indirectly failed
   delete indirect_failues
   log_fn  = log_dir "/broken_packages.txt"
   indirect_broken_found = 0
   for (pkgp in all_pkgpaths){
      if ((pkgpath SUBSEP pkgp) in deps){
         indirect_broken_found = 1

         indirect_failues [pkgp] = 1

         pkgp_log_dir = reports_dir "/" pkgp
         pkgp_log_fn  = pkgp_log_dir "/failed_because.txt"
         print pkgpath >> pkgp_log_fn
         xclose(pkgp_log_fn) # in order to not exceed system/awk limits...

         print pkgp > log_fn
      }
   }
   if (indirect_broken_found)
      xclose(log_fn) # in order to not exceed system/awk limits...

   # writing new queue
   printf "" > tmp_fn
   for (i in counts){
      if (! (i in indirect_failues)){
         print i, counts [i] > tmp_fn
      }
   }
   xclose(tmp_fn)

   # renaming
   xsystem("mv " tmp_fn " " queue_fn)

   # removing lock
   xsystem(rm_lock)

   next
}
'
}

verbose_print "Building\n"
runpipe0 \
    print_tasks '|' \
    ~/prjs/paexec/paexec -EI -lr -n +5 -c "env $environ ./distbb_slave" '|' \
    postfilter

######################################################################
## remove empty category dirs
verbose_print "Logs generation and clean-ups\n"
rmdir $REPORTS_DIR/* 2>/dev/null || true
