#!/bin/sh

set -e

######################################################################

header (){
    printf ' --**--**-- %8s --**--**--\n' "$1"
}

######################################################################

usage (){
    cat <<EOF
usage: distbb_slave node
EOF
}

if test $# -ne 2; then
    usage
    exit 1
fi

node=$1
fake_cmd=$2
shift
shift

do_this (){
    mkdir -p $REPORTS_DIR/$pkgpath
    header build
    echo "building $pkgpath...done"
}

while read pkgpath; do
    echo "package $pkgpath"
    do_this | uuencode -
    echo ''
done
