#!/bin/sh

set -e
. pipestatus

######################################################################

header (){
    printf ' --**--**-- %8s --**--**--\n' "$1"
}

######################################################################

build_package (){
    for t in $TARGETS; do
	header $t
	awk 'BEGIN {for (i=0; i < 1000; ++i) {print "zzzz", i} }'
	echo "stage $t...done"
	case "$t:$1" in
	    build:x11/compositeproto)
		return 75;;
	    package:x11/damageproto)
		return 76;;
	    depends:x11/editres|package:x11/bigreqsproto|install:x11/imwheel)
		return 77;;
	    *)
		;;
	esac
    done
}

while read pkgpath; do
    if runpipe_re '. 0' build_package $pkgpath '|' uuencode -; then
	echo "status: $pipestatus_1"
    else
	echo "status: 1" # uuencode failed
    fi
    echo '' # end of task
done
